#! /usr/bin/env python

import socket
import sys

if len(sys.argv) != 3:
    print >>sys.stderr, 'Usage: %s <hostname> <port>' % sys.argv[0]
    sys.exit(1)

hostname = sys.argv[1]
port = int(sys.argv[2])

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((hostname, port))

s.send("GET / HTTP/1.0\r\n\r\n")

while 1:
    buf = s.recv(1)
    if not buf:
        break
    sys.stdout.write(buf)

s.close()

